const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');

async function run_checks() {
    const output_path = process.env.QA_OUTPUT_PATH || path.resolve(__dirname, 'artifacts');
    await fs.mkdir(output_path, { recursive: true });
    const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH, headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 });
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    const base_url = process.env.APP_URL || 'http://127.0.0.1:4174/';
    try {
        await page.goto(base_url);
        await page.evaluate(() => document.fonts.ready);
        assert.equal(await page.evaluate(() => document.fonts.check('560 20px "Bricolage Grotesque"')), true);
        await page.screenshot({ path: path.join(output_path, 'empty_desktop.png'), fullPage: true });
        const fixture_data = await page.evaluate(() => {
            const canvas = document.createElement('canvas');
            canvas.width = 1440;
            canvas.height = 900;
            const context = canvas.getContext('2d');
            context.fillStyle = '#edeee9';
            context.fillRect(0, 0, 1440, 900);
            context.fillStyle = '#24362e';
            context.fillRect(0, 0, 1440, 95);
            context.fillStyle = '#edeee9';
            context.font = '28px sans-serif';
            context.fillText('ATELIER / 08', 64, 61);
            context.font = '19px sans-serif';
            context.fillText('Collection       Notre approche       Contact', 900, 57);
            context.fillStyle = '#d5d9cc';
            context.fillRect(760, 147, 616, 596);
            context.fillStyle = '#24362e';
            context.font = '76px sans-serif';
            context.fillText('Des objets', 64, 296);
            context.fillText('qui traversent', 64, 390);
            context.fillText('le temps.', 64, 484);
            context.font = '23px sans-serif';
            context.fillText('Le sens du détail, la simplicité en plus.', 68, 552);
            context.fillRect(68, 608, 255, 62);
            context.fillStyle = '#edeee9';
            context.font = '20px sans-serif';
            context.fillText('Voir la collection   ↗', 92, 648);
            context.fillStyle = '#91a084';
            context.beginPath();
            context.ellipse(1064, 624, 203, 37, 0, 0, Math.PI * 2);
            context.fill();
            context.fillStyle = '#b4724d';
            context.beginPath();
            context.roundRect(965, 382, 200, 237, [20, 20, 80, 80]);
            context.fill();
            context.fillStyle = '#7b4933';
            context.beginPath();
            context.ellipse(1065, 387, 98, 28, 0, 0, Math.PI * 2);
            context.fill();
            context.fillStyle = '#b4724d';
            context.fillRect(1008, 276, 112, 119);
            context.fillStyle = '#7b4933';
            context.beginPath();
            context.ellipse(1064, 280, 56, 15, 0, 0, Math.PI * 2);
            context.fill();
            context.fillStyle = '#75816f';
            context.font = '17px sans-serif';
            context.fillText('01 / Terre brute', 793, 708);
            context.fillStyle = '#a3ab9c';
            context.fillRect(64, 799, 1312, 1);
            context.fillStyle = '#57634f';
            context.font = '19px sans-serif';
            context.fillText('Pensé pour durer.', 64, 844);
            return canvas.toDataURL('image/png').split(',')[1];
        });
        const fixture_path = path.join(output_path, 'sample_image.png');
        await fs.writeFile(fixture_path, Buffer.from(fixture_data, 'base64'));
        await page.locator('#file_input').setInputFiles(fixture_path);
        await page.locator('#workspace_section').waitFor({ state: 'visible' });
        assert.equal(await page.locator('#export_button').isDisabled(), true);
        let image_bounds = await page.locator('#image_surface').boundingBox();
        await page.mouse.click(image_bounds.x + image_bounds.width * 0.23, image_bounds.y + image_bounds.height * 0.43);
        await page.locator('#comment_input').fill('Donner un peu plus d’air au titre. La troisième ligne est trop proche du texte de présentation.');
        await page.locator('#save_button').click();
        assert.equal(await page.locator('.comment_row').count(), 1);
        await page.locator('#area_button').click();
        image_bounds = await page.locator('#image_surface').boundingBox();
        await page.mouse.move(image_bounds.x + image_bounds.width * 0.65, image_bounds.y + image_bounds.height * 0.28);
        await page.mouse.down();
        await page.mouse.move(image_bounds.x + image_bounds.width * 0.83, image_bounds.y + image_bounds.height * 0.71, { steps: 12 });
        await page.mouse.up();
        await page.locator('#comment_input').fill('Éclaircir légèrement le visuel pour mieux faire ressortir la matière. Garder cette teinte terre cuite.');
        await page.locator('#save_button').click();
        assert.equal(await page.locator('.comment_row').count(), 2);
        assert.equal(await page.locator('#marker_layer .area_marker').count(), 1);
        const badge_offset = await page.locator('#marker_layer .area_marker').evaluate((marker) => {
            const area_bounds = marker.getBoundingClientRect();
            const badge_bounds = marker.querySelector('.marker_badge').getBoundingClientRect();
            return {
                x: badge_bounds.x + badge_bounds.width / 2 - area_bounds.x,
                y: badge_bounds.y + badge_bounds.height / 2 - area_bounds.y
            };
        });
        assert.ok(Math.abs(badge_offset.y) < 3);
        assert.ok(Math.abs(badge_offset.x) < 3);
        await page.locator('.edit_button').first().click();
        await page.locator('#comment_input').fill('Donner plus d’air au titre et à la présentation. Prévoir au moins 32 px entre ces deux éléments.');
        await page.locator('#save_button').click();
        assert.match(await page.locator('.comment_text').first().textContent(), /32 px/u);
        await page.locator('#point_button').click();
        await page.locator('#image_surface').focus();
        await page.keyboard.press('Enter');
        await page.keyboard.press('ArrowRight');
        await page.keyboard.press('Enter');
        await page.locator('#comment_input').fill('Le bouton doit être visible dès le premier écran, y compris sur mobile.');
        await page.keyboard.press('Control+Enter');
        assert.equal(await page.locator('.comment_row').count(), 3);
        await page.locator('#image_surface').focus();
        await page.keyboard.press('Enter');
        await page.locator('#comment_input').fill('Brouillon temporaire');
        assert.equal(await page.locator('#export_button').isDisabled(), true);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('#comment_input').isDisabled(), true);
        await page.evaluate(() => window.scrollTo(0, 0));
        await page.screenshot({ path: path.join(output_path, 'editor_desktop.png'), fullPage: true });
        const coordinates_before = await page.locator('#marker_layer .annotation_marker').evaluateAll((markers) => markers.map((marker) => [marker.style.left, marker.style.top, marker.style.width, marker.style.height]));
        await page.locator('#export_button').click();
        await page.locator('#export_dialog').waitFor({ state: 'visible' });
        const download_promise = page.waitForEvent('download');
        await page.locator('#download_link').click();
        const download = await download_promise;
        const png_path = path.join(output_path, 'export_result.png');
        await download.saveAs(png_path);
        const png = await fs.readFile(png_path);
        assert.equal(png.subarray(1, 4).toString(), 'PNG');
        assert.equal(png.readUInt32BE(16), 2400);
        assert.ok(png.readUInt32BE(20) > 2000);
        assert.equal(download.suggestedFilename(), 'sample_image_notes.png');
        await page.screenshot({ path: path.join(output_path, 'export_dialog.png') });
        await page.locator('#close_export_button').click();
        await page.setViewportSize({ width: 390, height: 844 });
        await page.evaluate(() => window.scrollTo(0, 0));
        await page.screenshot({ path: path.join(output_path, 'editor_mobile.png'), fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
        const coordinates_after = await page.locator('#marker_layer .annotation_marker').evaluateAll((markers) => markers.map((marker) => [marker.style.left, marker.style.top, marker.style.width, marker.style.height]));
        assert.deepEqual(coordinates_after, coordinates_before);
        await page.locator('.delete_button').nth(1).click();
        assert.equal(await page.locator('.comment_row').count(), 2);
        assert.deepEqual(await page.locator('#marker_layer .marker_badge').allTextContents(), ['1', '2']);
        await page.locator('#file_input').setInputFiles(fixture_path);
        await page.locator('#replace_dialog').waitFor({ state: 'visible' });
        await page.locator('#cancel_replace_button').click();
        assert.equal(await page.locator('.comment_row').count(), 2);
        await page.locator('#file_input').setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('invalid image') });
        await page.locator('#confirm_replace_button').click();
        await page.waitForFunction(() => document.getElementById('live_status').classList.contains('error'));
        assert.equal(await page.locator('.comment_row').count(), 2);
        await page.locator('#file_input').setInputFiles(fixture_path);
        await page.locator('#confirm_replace_button').click();
        await page.waitForFunction(() => document.querySelectorAll('.comment_row').length === 0);
        const long_text = 'Texte sur plusieurs lignes.\n\n' + 'SansEspace'.repeat(70) + '\nAccents : éàçœ. Emoji : 👨‍👩‍👧‍👦 🌍.';
        await page.locator('#image_surface').focus();
        await page.keyboard.press('Enter');
        await page.locator('#comment_input').fill(long_text);
        await page.locator('#save_button').click();
        await page.locator('#export_button').click();
        await page.locator('#export_dialog').waitFor({ state: 'visible' });
        const long_download_promise = page.waitForEvent('download');
        await page.locator('#download_link').click();
        await (await long_download_promise).saveAs(path.join(output_path, 'long_text_export.png'));
        await page.locator('#close_export_button').click();
        const export_checks = await page.evaluate(async () => {
            const context = document.createElement('canvas').getContext('2d');
            set_export_font(context, 22);
            const lines = wrap_export_text(context, 'a'.repeat(1200), 400);
            const widths_fit = lines.every((line) => context.measureText(line).width <= 400);
            let limit_error = '';
            try {
                await create_annotation_png(document.getElementById('source_image'), 'maximum.png', Array.from({ length: 40 }, () => ({ type: 'point', x: 0.5, y: 0.5, text: 'W'.repeat(1200) })));
            } catch (error) {
                limit_error = error.message;
            }
            return { widths_fit, limit_error };
        });
        assert.equal(export_checks.widths_fit, true);
        assert.match(export_checks.limit_error, /trop de texte/u);
        const drop_page = await browser.newPage({ viewport: { width: 390, height: 844 } });
        await drop_page.goto(base_url);
        await drop_page.screenshot({ path: path.join(output_path, 'empty_mobile.png'), fullPage: true });
        await drop_page.evaluate((base64) => {
            const bytes = Uint8Array.from(atob(base64), (character) => character.charCodeAt(0));
            const transfer = new DataTransfer();
            transfer.items.add(new File([bytes], 'dropped_image.png', { type: 'image/png' }));
            document.getElementById('drop_zone').dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: transfer }));
        }, fixture_data);
        await drop_page.locator('#workspace_section').waitFor({ state: 'visible' });
        assert.equal(await drop_page.locator('#file_name').textContent(), 'dropped_image.png');
        assert.deepEqual(errors, []);
        console.log(JSON.stringify({ result: 'passed', scenarios: ['import', 'point', 'area', 'edit', 'keyboard', 'cancel', 'export_download', 'responsive_coordinates', 'delete_renumber', 'replace_cancel', 'invalid_preserves_work', 'replace', 'long_text', 'export_limits', 'drag_drop'], png: { width: png.readUInt32BE(16), height: png.readUInt32BE(20), bytes: png.length }, output_path }, null, 2));
    } finally {
        await browser.close();
    }
}

run_checks().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
